openapi: 3.0.0
info:
  title: Pokemon Documentation
  description: This is a Pokemon API
  version: 1.0.0
  contact:
    email: georgetonjr@gmail.com
servers:
  - url: /
paths:
  /pokemons:
    post:
      tags:
        - Pokemons
      summary: Create a Pokemon
      description: Create a Pokemon based on passed parameters
      requestBody:
        content:
          application/json:
            schema:
              properties:
                tipo: 
                  description: Tipo do pokemon
                  type: string
                treinador:
                  description: Nome do treinador
                  type: string
      responses: 
        200:
          description: Created
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Pokemon'
        400:
          description: Bad request
        500:
          description: Internal server error
    get:
      tags:
        - Pokemons
      summary: List all pokemons
      description: List All pokemons
      responses:
        200:
          description: Get
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Pokemon'
        400:
          description: Bad request
        404:
          description: Pokemon not found
        500:
          description: Internal server error
  /pokemons/{pokemonId}:
    get:
      parameters:
          - name: pokemonId
            in: path
            required: true
            description: Parameter description in CommonMark or HTML.
            schema:
              type : integer
              minimum: 1
      tags:
        - Pokemons
      summary: Get a pokemon
      responses:
        200: 
          description: Get
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Pokemon'
    put:
      parameters:
          - name: pokemonId
            in: path
            required: true
            description: Parameter description in CommonMark or HTML.
            schema:
              type : integer
              minimum: 1
      tags:
        - Pokemons
      summary: Update a pokemon
      requestBody:
        content:
          application/json:
            schema:
              properties:
                treinador:
                  description: Nome do treinador
                  type: string
      responses:
        204: 
          description: No content
        400:
          description: Bad request
        404:
          description: Pokemon not found
        500:
          description: Internal server error
    delete:
      parameters:
          - name: pokemonId
            in: path
            required: true
            description: Parameter description in CommonMark or HTML.
            schema:
              type : integer
              minimum: 1
      tags:
        - Pokemons
      summary: Delete a pokemon
      responses:
        204: 
          description: No content
        400:
          description: Bad request
        404:
          description: Pokemon not found
        500:
          description: Internal server error
  /batalhar/{pokemonAId}/{pokemonBId}:
    post:
      tags:
        - Batalhar
      parameters:
        - name: pokemonAId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            minimum: 1
        - name: pokemonBId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            minimum: 1
      responses:
        200: 
          description: put
          content: 
            application/json:
              schema:
                properties:
                  vencedor:
                    $ref: '#/components/schemas/Pokemon'
                  perdedor: 
                    $ref: '#/components/schemas/loserPokemonReponse'
        400:
          description: Bad request
        404:
          description: Pokemon not found
        500:
          description: Internal server error
                
components:
  schemas:
    Pokemon:
      properties:
        id:
          type: number
          minimum: 1
        tipo:
          type: string
        treinador:
          type: string
        nivel:
          type: number
          minimum: 1
    loserPokemonReponse:
      properties:
        id:
          type: number
          minimum: 1
        tipo:
          type: string
        treinador:
          type: string
        nivel:
          type: number
          minimum: 1
        message: 
          type: string
        